### ISSUE TITLE
[Bug] Api Key not set for custom Api

### ISSUE THREAD

**Issue by dansiegel** [myci-actions/publish-nuget#1]
# Description

When pushing to a custom API the push will fail as being unauthenticated.

https://github.com/myci-actions/publish-nuget/blob/409d4f6631f3a03c43468a806bc21790388f60cc/action.yml#L20-L22

The issue is that when setting the API key no source is provided thus it defaults to NuGet.org

## Proposed Change

This could be changed in one of two ways...

```yml
nuget  setApiKey ${{ inputs.api-key }} -Source ${{ inputs.repo-url }}
```

or you could actually eliminate the setApiKey step entirely and simply add the ApiKey parameter when pushing.

```yml
nuget push $_.FullName -Source ${{ inputs.repo-url }} -ApiKey ${{ input.api-key }} -SkipDuplicate
```

**Comment by igagis** [comment]
Thanks for reporting the problem and even proposing solutions!

I decided to go with the second solution you proposed. I made the change on the `api_key` branch. Could you test it:
```
uses: myci-actions/publish-nuget@api_key
```

and as soon as you report it works I will release a new version of the action.

**Comment by dansiegel** [comment]
I actually had done that in a fork but seems Actions aren't so easy to PR back to the source 😆 

That does work though... FYI you can get rid of the whole loop... if you pass `nuget push *.nupkg` it will iterate automatically... it doesn't require a full file name

**Comment by igagis** [comment]
Ok, version 3 released to marketplace. Thanks for testing!

>  FYI you can get rid of the whole loop... if you pass nuget push *.nupkg it will iterate automatically

The intention is to publish only files listed in the action's input `filename` argument, not all the nuget files, so I think the loop is still needed.

**Comment by dansiegel** [comment]
so there are effectively three scenarios you might see...

- SomePackageName.1.0.0.nupkg
- SomePack*.nupkg
- *.nupkg

If you have the first one there's no need to iterate... if you have either of the other two an iteration would need to occur, however the NuGet cli client is actually smart enough to handle this automatically... it also prints to the console which package or symbols package is being pushed and to what endpoint

**Comment by igagis** [comment]
yes, you are right!
I'll fix it

**Comment by igagis** [comment]
Please check #3 , should it be like this?

**Comment by igagis** [comment]
Thanks! Version 4 released to the marketplace.
